version: "3.8"

services:

  # Builds the frontend Docker image and creates the frontend microservice
  yolo-client:
    image: jorashid/yolo-frontend:v1.0.6
    build: ./client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - yolo-net

  # Builds the backend Docker image and creates the backend microservice
  yolo-backend:
    image: jorashid/yolo-backend:v1.0.0
    build: ./backend
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    environment:
       - MONGODB_ATLAS=mongodb+srv://james_rashid:james_rashid@cluster0.zsanm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    volumes:
      - app-mongo-data:/app/data  # Attach the volume to persist data
    networks:
      - yolo-net

# Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  yolo-net:
    name: yolo-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

# Creates a Docker volume that persists all the data stored in the database
volumes:
  app-mongo-data:
    driver: local
